### ISSUE TITLE
Syntax error in export

### ISSUE THREAD

**Issue by creatzor** [blockchain-etl/ethereum-etl-postgres#10]
Using the command: `bash ethereum_bigquery_to_gcs.sh` starts working for about a minute then hits a syntax error. At the end of the command's run, no data exists in GCP storage.

Tried it on M1 mac and on Ubuntu 18, same result.

```
Exporting BigQuery table bigquery-public-data:crypto_ethereum.blocks
Extracting bigquery-public-data:crypto_ethereum.blocks to gs://<BUCKET>/bigquery-public-data:crypto_ethereum.block
s_raw/*.gz ...
Waiting on bqjob_r8e927cc0dccab5b_0000017dc4db78a2_1 ... (3s) Current status: DONE   
Traceback (most recent call last):
  File "ethereumetl_postgres/gcs_compose.py", line 3, in <module>
    from google.cloud import storage
ImportError: No module named google.cloud
Traceback (most recent call last):
  File "ethereumetl_postgres/gcs_compose.py", line 3, in <module>
    from google.cloud import storage
ImportError: No module named google.cloud
```

```
CommandException: 1 files/objects could not be removed.
Exporting BigQuery table export_temp_dataset.flattened_logs
Extracting export_temp_dataset.flattened_logs to gs://<BUCKET>/export_temp_dataset.flattened_logs_raw/*.gz ...
Waiting on bqjob_r531741fce7ae2a07_0000017dc4c47fcc_1 ... (33s) Current status: DONE   
  File "ethereumetl_postgres/gcs_compose.py", line 20
    print('Composing files in {} to {}'.format(f'gs://{bucket_name}{source_prefix}', f'gs://{bucket_name}{destinati
on_prefix}'))
                                                                                  ^
SyntaxError: invalid syntax
  File "ethereumetl_postgres/gcs_compose.py", line 20
    print('Composing files in {} to {}'.format(f'gs://{bucket_name}{source_prefix}', f'gs://{bucket_name}{destinati
on_prefix}'))
                                                                                  ^
SyntaxError: invalid syntax
```

**Comment by creatzor** [comment]
For the export to work as expected, google-cloud-bigquery must be installed prior.

`pip install google-cloud-bigquery`

**Comment by creatzor** [comment]
My initial error was resolved, but new errors popped up.

```
  File "ethereumetl_postgres/gcs_compose.py", line 20
    print('Composing files in {} to {}'.format(f'gs://{bucket_name}{source_prefix}', f'gs://{bucket_name}{destination_prefix}'))
                                                                                  ^
SyntaxError: invalid syntax
  File "ethereumetl_postgres/gcs_compose.py", line 20
    print('Composing files in {} to {}'.format(f'gs://{bucket_name}{source_prefix}', f'gs://{bucket_name}{destination_prefix}'))
                                                                                  ^
SyntaxError: invalid syntax
If you experience problems with multiprocessing on MacOS, they might be related to https://bugs.python.org/issue33725. You can disable multiprocessing by editing your .boto config or by adding the following flag to your command: `-o "GSUtil:parallel_process_count=1"`. Note that multithreading is still available even if you disable multiprocessing.

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2366, in run
Removing gs://<BUCKET>/bigquery-public-data:crypto_ethereum.transactions_raw/000000000000.gz#1639779463953282...
    cls = copy.copy(class_map[caller_id])
  File "<string>", line 2, in __getitem__
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 507, in Client
    c = SocketClient(address)
  File "/opt/homebrew/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/connection.py", line 635, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

**Comment by creatzor** [comment]
It seems the script doesn't play well with aliased python. I changed https://github.com/blockchain-etl/ethereum-etl-postgres/blob/master/bigquery_to_gcs.sh#L29 and https://github.com/blockchain-etl/ethereum-etl-postgres/blob/master/bigquery_to_gcs.sh#L30 to use python3 instead of python. Step 1 of the import works now
